services:
  postgres:
    image: postgres
    container_name: psql-db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=bus
      - POSTGRES_USER=bus
      - POSTGRES_DB=busdb
    expose:
      - 5432
    networks:
      - psql-network
  basic-server:
    build: .
    image: kotlin-ktor-starter
    container_name: kotlin-ktor-server
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      APP: /opt/applications/basic-server.jar
    expose:
      - 8888
    networks:
      - psql-network
  data-analyzer:
    image: kotlin-ktor-starter
    container_name: kotlin-ktor-analyzer
    ports:
      - "8887:8887"
    environment:
      PORT: 8887
      APP: /opt/applications/data-analyzer-server.jar
      DB_URL: jdbc:postgresql://postgres:5432/busdb
      DB_USER: bus
      DB_PASSWORD: bus
    expose:
      - 8887
    networks:
      - psql-network
    depends_on:
      - postgres
  data-collector:
    image: kotlin-ktor-starter
    container_name: kotlin-ktor-collector
    ports:
      - "8886:8886"
    environment:
      PORT: 8886
      APP: /opt/applications/data-collector-server.jar
      ANALYZER_URL: http://data-analyzer:8887/tasks
      TransitToken: ea43df0e-f500-4422-83a5-f00910b6b2d5
    expose:
      - 8886
    networks:
      - psql-network
    depends_on:
      - data-analyzer
networks:
  psql-network:
    driver: bridge

